baseURL: https://3mr.fr/
languageCode: en-au
title: mrfrase3
paginate: 10
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: mrfrase3
  description: Coder Extraordinaire & Emotional Support Budgie
  keywords: [Blog, Notes, Software]
  author: Fraser
  # author: ["Me", "You"] # multiple authors
  images: ["/profile.png"]
  DateFormat: "Jan 2, 2006"
  defaultTheme: dark #auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  mainSections:
    - projects
    - notes
    - blog


  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"
    theme_color: "#8bc33e"

  label:
    text: "mrfrase3"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "mrfrase3"
    Content: Coder Extraordinaire & Emotional Support Budgie

  socialIcons:
    - name: twitter
      url: "https://twitter.com/mrfrase3"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/mrfrase3"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page
    direction: "left"

  editPost:
    # URL: "https://github.com/<path_to_repo>/content"
    # Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: üîç
      url: /search/
      weight: 10
    - identifier: categories
      name: üóÑÔ∏è
      url: /categories/
      weight: 11
    - identifier: tags
      name: üè∑Ô∏è
      url: /tags/
      weight: 12
    - identifier: blog
      name: blog
      url: /blog/
      weight: 20
    - identifier: notes
      name: notes
      url: /notes/
      weight: 21
    - identifier: projects
      name: projects
      url: /projects/
      weight: 21
    # - identifier: duinoapp
    #   name: duino.app
    #   url: https://duino.app
    #   weight: 30
    # - identifier: slaxpro
    #   name: slax.pro
    #   url: https://slax.pro
    #   weight: 40
    - identifier: github
      name: github
      url: https://github.com/mrfrase3
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
